### PR TITLE
language.json

### PR DESCRIPTION
**Pull request by CennoxX**
corrected german typo "flexieble" to "flexible"

### CODE REVIEW

**Comment by ireun** [comment]
@Yonezpt Do we accept translations made as pull request? Or only these made on Crowdin?

**Comment by Yonezpt** [comment]
@ireun This is something I do not know, you will have to clear that with YePpHa

**Comment by CennoxX** [comment]
Thanks, I didn't know about Crowdin, I'll use that.

**Comment by ireun** [comment]
Alright, so i will close this request, 

@Yonezpt I think we don't.. (https://github.com/YePpHa/YouTubeCenter/pull/1903)

**Comment by YePpHa** [comment]
To answer @ireun question. We do not allow translation made as pull requests. It's only done through Crowdin.

**Pull request closed without merging**
