### PR TITLE
Update to YouTube Data API (v3) and new page structure

### PR DESCRIPTION
**Pull request by Choonster**
Version 2 of the YouTube API has been shut down, so I've replaced all uses of it with the corresponding version 3 endpoints.

The structure of the comments section of the `watch` page has changed, so I've updated the comment country flags to use the new structure.

I didn't include a built version of the Safari extension because I didn't want to sign up to Apple's Developer Program.

### CODE REVIEW

**Comment by thinkpad4** [comment]
Thank you for this, would you be able to maintain this in the short term?  Like updating it to the new youtube look?

**Comment by Choonster** [comment]
I may be able to make small fixes here and there, but I can't promise anything major.

**Comment by thinkpad4** [comment]
Something is better than having it die off

**Comment by YePpHa** [comment]
Seems fine.

**Pull request merged**
